services:
  giropops-senhas:
    image: lfbrand90/linuxtips-giropops-senhas:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: giropops-senhas
    ports:
      - "8000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"